--
-- File generated with SQLiteStudio v3.2.1 on Mon Sep 14 15:45:00 2020
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Log
CREATE TABLE Log (LogEntryId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Emp_id INTEGER CONSTRAINT Emp_idConstraint REFERENCES Login (Emp_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL, LotNum VARCHAR REFERENCES Sample (LotNum) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL, WhenModifed DATETIME NOT NULL, Patient_id VARCHAR (12), Rep_id VARCHAR (12), LogType CHAR (1) NOT NULL);

-- Table: Login
CREATE TABLE Login (Emp_id NUMERIC PRIMARY KEY NOT NULL UNIQUE, Pin VARCHAR (6) NOT NULL, IsActive BOOLEAN NOT NULL);

-- Table: Sample
CREATE TABLE Sample (
  LotNum VARCHAR PRIMARY KEY NOT NULL UNIQUE,
  NameandDosage VARCHAR (50) NOT NULL,
  Count INTEGER NOT NULL,
  ExpirationDate DATE NOT NULL,
  isExpired BOOLEAN NOT NULL
  );

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
