//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace InventorySystem
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Log>();
                db.CreateTable<Login>();
                db.CreateTable<Sample>();
            }
        }
    }
    public partial class Log
    {
        [PrimaryKey, AutoIncrement]
        public Int64 LogEntryId { get; set; }
        
        [NotNull]
        public Int64 Emp_id { get; set; }
        
        [NotNull]
        public String LotNum { get; set; }
        
        [NotNull]
        public DateTime WhenModifed { get; set; }
        
        public Object Patient_id { get; set; }
        
        public Object Rep_id { get; set; }
        
        [NotNull]
        public Object LogType { get; set; }
        
    }
    
    public partial class Login
    {
        [PrimaryKey]
        public Decimal Emp_id { get; set; }
        
        [NotNull]
        public Object Pin { get; set; }
        
        [NotNull]
        public Boolean IsActive { get; set; }
        
    }
    
    public partial class Sample
    {
        [PrimaryKey]
        public String LotNum { get; set; }
        
        [NotNull]
        public Object NameandDosage { get; set; }
        
        [NotNull]
        public Int64 Count { get; set; }
        
        [NotNull]
        public DateTime ExpirationDate { get; set; }
        
        [NotNull]
        public Boolean isExpired { get; set; }
        
    }
    
}
